# Generated by Django 3.1.7 on 2021-03-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210308_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionHouse',
            new_name='AuctionListing',
        ),
    ]
