# Generated by Django 3.1.7 on 2021-03-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210308_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comment_contents', to='auctions.Comments'),
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.ManyToManyField(blank=True, related_name='current_bid', to='auctions.Bids'),
        ),
    ]
