# Generated by Django 3.1.7 on 2021-03-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210309_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='active_listing',
            field=models.BooleanField(default=True),
        ),
    ]
