# Generated by Django 3.1.7 on 2021-03-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210309_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='category',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ManyToManyField(related_name='category_type', to='auctions.Categories'),
        ),
    ]
