# Generated by Django 3.1.7 on 2021-03-11 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210311_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='auctions.bids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.RemoveField(
            model_name='bids',
            name='user',
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='auction_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_lists', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
