# Generated by Django 3.1.7 on 2021-03-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210311_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default='gday'),
        ),
    ]
