# Generated by Django 3.1.7 on 2021-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210311_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
